In [6]:
import pandas as pd

In [7]:
hike_df = pd.read_csv('./data/hiking.csv')
hike_df

,Activity Type,Date,Favorite,Title,Distance,Calories,Time,Avg HR,Max HR,Aerobic TE,...,Body Battery Drain,Min Temp,Decompression,Best Lap Time,Number of Laps,Max Temp,Moving Time,Elapsed Time,Min Elevation,Max Elevation
0,Hiking,2026-02-08 11:07:50,False,San Diego Hiking,1.61,354,00:53:27,113,178,2.0,...,-7,78.8,No,00:53:27,1,95.0,00:27:58,00:56:19,-2,318
1,Hiking,2026-01-15 08:53:55,False,Amecameca Hiking,5.05,"1,482",02:57:08,136,180,3.2,...,-17,68.0,No,02:57:08,1,84.2,01:56:43,03:27:25,"12,089","13,083"

In [8]:
run_df = pd.read_csv('./data/runs.csv')
run_df

,Activity Type,Date,Favorite,Title,Distance,Calories,Time,Avg HR,Max HR,Aerobic TE,...,Body Battery Drain,Min Temp,Decompression,Best Lap Time,Number of Laps,Max Temp,Moving Time,Elapsed Time,Min Elevation,Max Elevation
0,Running,2026-02-15 14:16:17,False,Chicago Running,1.23,155,00:12:40,142,168,2.2,...,-3,59.0,No,00:02:16.7,2,64.4,00:12:29,00:15:37,590,617
1,Running,2026-02-15 12:37:56,False,Chicago Running,6.87,861,01:03:05,157,191,3.8,...,-16,57.2,No,00:08:04.7,7,77.0,01:02:29,01:33:15,581,606
2,Running,2026-02-15 12:09:52,False,Chicago Running,2.31,313,00:21:40,164,189,3.1,...,-6,66.2,No,00:02:51.6,3,77.0,00:21:20,00:23:00,730,743
3,Running,2026-02-14 19:57:40,False,Chicago Running,0.93,116,00:08:10.4,155,174,2.2,...,-2,75.2,No,00:08:10.4,1,80.6,00:07:45,00:09:17.7,741,748
4,Running,2026-02-14 15:29:37,False,Chicago Running,2.28,278,00:19:36,158,185,3.0,...,-7,64.4,No,00:02:15.6,3,71.6,00:18:45,00:22:11,737,747
5,Treadmill Running,2026-02-11 15:54:09,False,Treadmill Running,3.01,380,00:33:22,141,164,2.7,...,-7,78.8,No,00:00:09.4,4,84.2,00:32:13,00:33:22,--,--
6,Running,2026-02-06 15:57:06,False,San Marcos Running,2.01,229,00:15:30,169,201,3.0,...,-5,69.8,No,00:00:05.7,3,78.8,00:15:24,00:16:08,888,"1,589"
7,Running,2026-02-06 15:06:43,False,San Marcos Running,2.24,359,00:25:49,165,185,3.2,...,-7,75.2,No,00:03:25.8,3,84.2,00:25:22,00:27:47,899,"1,583"
8,Running,2026-02-05 15:08:40,False,San Marcos Running,3.14,421,00:31:36,155,201,3.2,...,-7,73.4,No,00:01:20.1,4,84.2,00:30:51,00:35:33,626,904
9,Treadmill Running,2026-02-02 16:56:14,False,Treadmill Running,1.01,135,00:12:09,136,160,1.9,...,-2,77.0,No,00:00:08.1,2,80.6,00:12:02,00:12:09,--,--
10,Treadmill Running,2026-02-01 21:17:53,False,Treadmill Running,3.11,406,00:36:18,140,163,2.7,...,-5,73.4,No,00:01:06.0,4,84.2,00:35:15,00:36:18,--,--
11,Track Running,2026-01-28 07:34:07,False,Track Running,"1,610",134,00:09:58.7,153,179,2.2,...,-2,73.4,No,00:00:00.7,9,78.8,00:09:39.9,00:09:59.5,625,629
12,Track Running,2026-01-27 17:49:02,False,Track Running,"4,910",354,00:30:27,143,198,2.8,...,-5,69.8,No,00:00:01.0,24,78.8,00:29:53,00:31:01,545,558
13,Running,2026-01-25 11:36:00,False,Chicago Running,1.36,186,00:13:14,163,191,2.8,...,-2,66.2,No,00:03:27.8,2,77.0,00:13:09,00:13:24,591,604
14,Treadmill Running,2026-01-24 10:10:33,False,Treadmill Running,3.04,383,00:31:02,148,166,3.0,...,-10,71.6,No,00:00:24.2,4,82.4,00:30:15,00:31:02,--,--
15,Treadmill Running,2026-01-21 18:40:35,False,Treadmill Running,1.12,140,00:12:07,140,151,2.0,...,-2,80.6,No,00:01:14.8,2,86.0,00:11:52,00:12:07,--,--
16,Running,2026-01-18 17:47:03,False,Running,0.87,135,00:10:04,156,190,2.5,...,--,71.6,No,00:10:04,1,78.8,00:08:55,00:12:57,"7,973","7,980"
17,Running,2026-01-14 09:03:48,False,Cuauhtémoc Running,0.48,54,00:04:54.1,134,145,0.8,...,-1,69.8,No,00:04:54.1,1,71.6,00:04:33,00:04:58.7,"6,520","6,528"
18,Treadmill Running,2026-01-09 19:06:44,False,Treadmill Running,1.52,215,00:18:09,143,162,2.3,...,-3,77.0,No,00:05:40.3,2,84.2,00:17:32,00:18:12,--,--
19,Running,2026-01-07 19:32:34,False,Chicago Running,1.77,230,00:16:54,159,181,2.8,...,-3,69.8,No,00:06:58.8,2,78.8,00:16:31,00:17:16,604,615

In [9]:
# run_df["Time"] = run_df["Time"].astype(str).str.replace(r"\.\d+$", "", regex=True)
run_df.loc[:, "Time"] = (
    run_df.loc[:, "Time"]
    .astype(str)
    .str.replace(r"\.\d+$", "", regex=True)
)

run_df.loc[:, "Distance"] = (
    run_df["Distance"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

run_df.loc[:, "Distance"] = pd.to_numeric(run_df["Distance"], errors="coerce")
track_mask = run_df["Title"] == "Track Running"

run_df.loc[track_mask, "Distance"] = (
    run_df.loc[track_mask, "Distance"] * 0.000621371
)
run_df.loc[:, "Distance"] = run_df["Distance"].round(2)

In [12]:
run_df.columns

Index(['Activity Type', 'Date', 'Favorite', 'Title', 'Distance', 'Calories',
       'Time', 'Avg HR', 'Max HR', 'Aerobic TE', 'Avg Run Cadence',
       'Max Run Cadence', 'Avg Pace', 'Best Pace', 'Total Ascent',
       'Total Descent', 'Avg Stride Length', 'Avg Vertical Ratio',
       'Avg Vertical Oscillation', 'Avg Ground Contact Time', 'Avg GAP',
       'Normalized Power® (NP®)', 'Training Stress Score®', 'Avg Power',
       'Max Power', 'Steps', 'Body Battery Drain', 'Min Temp', 'Decompression',
       'Best Lap Time', 'Number of Laps', 'Max Temp', 'Moving Time',
       'Elapsed Time', 'Min Elevation', 'Max Elevation'],
      dtype='object')

In [13]:
hike_df.columns

Index(['Activity Type', 'Date', 'Favorite', 'Title', 'Distance', 'Calories',
       'Time', 'Avg HR', 'Max HR', 'Aerobic TE', 'Avg Cadence', 'Max Cadence',
       'Avg Pace', 'Best Pace', 'Ascent', 'Total Descent', 'Avg Stride Length',
       'Training Stress Score®', 'Steps', 'Body Battery Drain', 'Min Temp',
       'Decompression', 'Best Lap Time', 'Number of Laps', 'Max Temp',
       'Moving Time', 'Elapsed Time', 'Min Elevation', 'Max Elevation'],
      dtype='object')

In [15]:
# Assuming hike_df and run_df are already defined DataFrames
# Convert hike_df to a list of dictionaries
hike_json = hike_df.to_json(orient='records')

# Convert run_df to a list of dictionaries
run_json = run_df.to_json(orient='records')

# Save the JSON strings to files
with open('hike_data.json', 'w') as hike_file:
    hike_file.write(hike_json)

with open('run_data.json', 'w') as run_file:
    run_file.write(run_json)